# SITE CONFIGURATION
baseurl: "/"
url: "https://KNET-KWU.github.io"

# THEME-SPECIFIC CONFIGURATION
title: K-NET KWU                                    # site's title
description: "K-NET 동아리 블로그입니다"      # used by search engines
avatar: assets/k-net-1to1.png                         # Empty for no avatar in navbar
favicon: assets/favicon.ico                               # Icon displayed in the tab

# Header and footer text
header_text: 광운대학교 동아리 K-NET 입니다!  # Change Blog header text
header_feature_image: assets/KNET_1.png
footer_text: "서울 노원구 광운로 20 광운대학교복지관 512호"

# Blog
excerpt: true                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: /assets/img/lineart.png                    # A bit transparent for color posts.

# Features
# More in the _data folder for share buttons, author and language
# For layout customization, go to the "_sass > base" folder, and check "_variables.scss"
katex: false                                             # Enable if using math markup
mermaid: true                                           # Enable mermaid-js for sequence and diagrams
google_analytics: G-Y4MGM242SK
cookie_consent: false                                   # To respect the usage of cookies
color_theme: auto                                       # auto, dark or light

# Comments
comments:
  disqus_shortname:                                     # Your discus shortname for comments
  cusdis_app_id:                                        # Your cusdis data-app-id
  utterances:                                           # Enable by filling below information. For more info, go to https://utteranc.es
    repo:                                               # your public comments repository (e.g. owner/repo)
    issue-term:                                         # Issue term (e.g. "comment" consider issues with this word in the title as comments)

# PAGINATION
paginate: 5
paginate_path: "/blog/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
sass:
  style: compressed
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
exclude: [".jekyll-cache", ".idea", "vendor/*", "assets/node_modules/*"]

# theme: type-on-strap                                  # if using the theme as a jekyll theme gem
remote_theme: sylhare/Type-on-Strap                     # If using as a remote_theme in github
